services:
  sim1:
    image: 7robertodantas/lnpay-smartmeter:latest
    container_name: sim1
    ports:
      - "3010:8080" # UI
    environment:
      - DEVICE_ID=smart-meter-001
      - DEVICE_SECRET=smart-meter-001_password
    env_file:
      - .env.simulators
    volumes:
      - ../infrastructure/certs/ca.crt:/certs/ca.crt:ro
    restart: unless-stopped

  sim2:
    image: 7robertodantas/lnpay-smartmeter:latest
    container_name: sim2
    ports:
      - "3011:8080" # UI
    environment:
      - DEVICE_ID=smart-meter-002
      - DEVICE_SECRET=smart-meter-002_password
    env_file:
      - .env.simulators
    volumes:
      - ../infrastructure/certs/ca.crt:/certs/ca.crt:ro
    restart: unless-stopped

  sim3:
    image: 7robertodantas/lnpay-smartmeter:latest
    container_name: sim3
    ports:
      - "3012:8080" # UI
    environment:
      - DEVICE_ID=smart-meter-003
      - DEVICE_SECRET=smart-meter-003_password
    env_file:
      - .env.simulators
    volumes:
      - ../infrastructure/certs/ca.crt:/certs/ca.crt:ro
    restart: unless-stopped

