---
lina_services:
  - name: ledger-service
    binary: ledger
    user: lina-ledger
    systemd_after: network-online.target redis-server.service
    systemd_wants: redis-server.service

  - name: lightning-service
    binary: lightning
    user: lina-lightning
    systemd_after: network-online.target redis-server.service
    systemd_wants: redis-server.service

  - name: consumption-service
    binary: consumption
    user: lina-consumption
    systemd_after: network-online.target redis-server.service ledger-service.service
    systemd_wants: redis-server.service ledger-service.service

  - name: device-service
    binary: device
    user: lina-device
    systemd_after: "network-online.target mosquitto.service redis-server.service ledger-service.service lightning-service.service"
    systemd_wants: "mosquitto.service redis-server.service ledger-service.service lightning-service.service"
